version: "3.8"

services:
  apache:
    image: httpd:latest
    container_name: hello-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:latest
    container_name: hello-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: hello_database
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
